/**
 * One-off restore: re-inserts "Software Company" org and its 25 job listings.
 * Run once, then delete this file.
 *
 * Usage:  npm run db:restore:software-company
 */

import { Pool } from 'pg';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('ERROR: DATABASE_URL not set'); process.exit(1); }

const ORG_ID   = 'org_3CGmXY8iZIYcF9eFcljH3YGbL5x';
const ORG_NAME = 'Software Company';
const PRIMARY_EMPLOYER_ID = 'user_3CGmVORUsSxzFqm7VISpBhmgBpT';

const pool = new Pool({ connectionString: DATABASE_URL });

function daysAgo(n: number): Date {
  const d = new Date(); d.setDate(d.getDate() - n); return d;
}

function desc(role: string, skills: [string,string,string,string], req: string[], nth: string[]): string {
  const [s1,s2,s3,s4] = skills;
  return [
    `## About the Role\n\nWe are looking for a talented ${role} to join our growing team. You will work on challenging problems at scale alongside a world-class engineering organization. This is a high-impact position where your contributions will be visible across the entire product.`,
    `## Responsibilities\n\n- Design, build, and maintain production-quality systems using ${s1} and ${s2}.\n- Collaborate with product, design, and data teams to ship features that delight users.\n- Write clean, testable, well-documented code and lead thorough code reviews.\n- Contribute to architectural decisions and help define engineering best practices.\n- Monitor system performance, identify bottlenecks, and drive reliability improvements.`,
    `## Requirements\n\n- 3+ years of professional experience with ${s1} in a production environment.\n- Strong proficiency in ${s2} and working knowledge of ${s3}.\n- Solid understanding of ${s4} and modern software engineering principles.\n${req.map(r=>`- ${r}`).join('\n')}`,
    `## Nice to Have\n\n- Experience with cloud-native infrastructure (AWS, GCP, or Azure).\n- Familiarity with containerization and orchestration (Docker, Kubernetes, Helm).\n${nth.map(r=>`- ${r}`).join('\n')}`,
    `## What We Offer\n\n- Competitive salary plus equity participation.\n- Flexible remote-first culture with async communication.\n- Annual learning budget ($2,000+) for courses, conferences, and certifications.\n- Top-tier hardware, health insurance, and unlimited PTO.`,
  ].join('\n\n');
}

type L = { title:string; description:string; wage:number|null; wageInterval:'hourly'|'yearly'|null; country:string; city:string; isFeatured:boolean; locationRequirement:'remote'|'hybrid'|'in-office'; experienceLevel:'junior'|'mid-level'|'senior'; status:'published'; type:'full-time'|'part-time'|'internship'; postedAt:Date };

const LISTINGS: L[] = [
  { title:'Senior Frontend Developer', description:desc('Senior Frontend Developer',['React','TypeScript','Next.js','CSS-in-JS / Tailwind CSS'],['Deep expertise in React hooks, context, and performance optimization patterns (memoization, code-splitting, lazy loading).','Proficiency building accessible (WCAG 2.1 AA) and responsive UI components.','Experience integrating REST or GraphQL APIs and managing client-side state (Zustand, Redux Toolkit, or React Query).'],['Contributions to open-source UI libraries or design systems.','Experience with micro-frontend architecture or monorepo tooling (Nx, Turborepo).']), wage:150000, wageInterval:'yearly', country:'Israel', city:'Tel Aviv', isFeatured:true, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(5) },
  { title:'Backend Engineer', description:desc('Backend Engineer',['Node.js','PostgreSQL','TypeScript','REST APIs'],['Solid understanding of relational database design, query optimization, and indexing strategies.','Experience building and maintaining high-throughput microservices or monolithic backends.','Familiarity with authentication/authorization patterns (OAuth 2.0, JWT, session management).'],['Experience with message queues (RabbitMQ, Kafka, or AWS SQS).','Knowledge of Redis or Memcached for caching and rate limiting.']), wage:130000, wageInterval:'yearly', country:'United States', city:'New York', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(12) },
  { title:'Fullstack Engineer', description:desc('Fullstack Engineer',['React','Node.js','TypeScript','PostgreSQL'],['Proven ability to own features end-to-end: from database schema design to polished UI.','Experience with server-side rendering frameworks (Next.js or Remix).','Comfort working across the full stack and switching context between frontend and backend.'],['Experience with serverless architectures (Vercel, AWS Lambda, or Cloudflare Workers).','Familiarity with CI/CD pipelines and automated deployment strategies.']), wage:170000, wageInterval:'yearly', country:'United States', city:'San Francisco', isFeatured:true, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(3) },
  { title:'DevOps Engineer', description:desc('DevOps Engineer',['Kubernetes','Terraform','AWS','CI/CD pipelines'],['Hands-on experience managing Kubernetes clusters in production (EKS, GKE, or AKS).','Strong infrastructure-as-code skills with Terraform or Pulumi.','Experience building and maintaining CI/CD pipelines (GitHub Actions, GitLab CI, or Jenkins).'],['Experience with GitOps workflows (ArgoCD or Flux).','Knowledge of observability stacks (Prometheus, Grafana, Loki, or Datadog).']), wage:120000, wageInterval:'yearly', country:'Germany', city:'Berlin', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(20) },
  { title:'Product Manager', description:desc('Product Manager',['product strategy','agile / scrum','user research','OKRs & roadmapping'],['Experience owning a product area end-to-end: discovery, prioritization, delivery, and iteration.','Ability to translate ambiguous business problems into clear, actionable requirements.','Strong data literacy — comfortable writing SQL queries and working with analytics dashboards.'],['Experience at a high-growth B2B SaaS or marketplace company.','Technical background or experience working closely with engineering teams.']), wage:110000, wageInterval:'yearly', country:'United Kingdom', city:'London', isFeatured:false, locationRequirement:'in-office', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(8) },
  { title:'Senior Data Scientist', description:desc('Senior Data Scientist',['Python','machine learning','scikit-learn / XGBoost','SQL & data pipelines'],['Experience building and deploying end-to-end machine learning models in production.','Strong statistical foundations: hypothesis testing, A/B experiments, regression analysis.','Proficiency with pandas, NumPy, and data visualization libraries (Matplotlib, Plotly, or Seaborn).'],['Experience with deep learning frameworks (PyTorch or TensorFlow).','Familiarity with MLOps tooling (MLflow, Weights & Biases, or SageMaker).']), wage:160000, wageInterval:'yearly', country:'Israel', city:'Tel Aviv', isFeatured:true, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(15) },
  { title:'ML Engineer', description:desc('ML Engineer',['PyTorch','Python','AWS SageMaker','distributed training'],['Experience training and serving large-scale machine learning models in production.','Knowledge of model optimization techniques: quantization, distillation, and ONNX export.','Familiarity with feature stores, vector databases, and retrieval-augmented generation (RAG) patterns.'],['Experience with LLM fine-tuning (LoRA, PEFT) or prompt engineering at scale.','Background in NLP, computer vision, or recommendation systems.']), wage:200000, wageInterval:'yearly', country:'United States', city:'San Francisco', isFeatured:false, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(7) },
  { title:'QA Automation Engineer', description:desc('QA Automation Engineer',['Playwright','TypeScript','Jest','CI/CD integration'],['Experience designing and maintaining large end-to-end test suites using Playwright or Cypress.','Solid understanding of test pyramid principles: unit, integration, and E2E coverage.','Experience integrating automated tests into CI/CD pipelines (GitHub Actions, CircleCI).'],['Experience with API testing tools (Postman, k6, or Supertest).','Knowledge of performance and load testing (Artillery, Locust, or k6).']), wage:90000, wageInterval:'yearly', country:'Israel', city:'Tel Aviv', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(25) },
  { title:'Cloud Architect', description:desc('Cloud Architect',['AWS','GCP','Terraform','multi-cloud networking'],['Proven track record designing enterprise-grade cloud architectures (VPCs, IAM, HA/DR patterns).','Deep expertise in cost optimization, resource governance, and FinOps best practices.','Experience leading cloud migration projects (lift-and-shift and re-architecture).'],['AWS or GCP professional-level certifications.','Experience with service mesh (Istio, Linkerd) and zero-trust networking.']), wage:210000, wageInterval:'yearly', country:'United States', city:'New York', isFeatured:false, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(30) },
  { title:'Mobile Engineer (React Native)', description:desc('Mobile Engineer (React Native)',['React Native','TypeScript','iOS & Android deployment','Expo'],['Experience shipping React Native apps to both the App Store and Google Play.','Solid understanding of native module bridging and platform-specific APIs.','Proficiency with state management in mobile contexts (Zustand, Jotai, or Redux Toolkit).'],['Experience with Expo EAS Build and OTA updates.','Familiarity with mobile performance profiling and crash analytics (Sentry, Crashlytics).']), wage:140000, wageInterval:'yearly', country:'United States', city:'Austin', isFeatured:true, locationRequirement:'remote', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(2) },
  { title:'Security Engineer', description:desc('Security Engineer',['application security','OWASP Top 10','penetration testing','SAST/DAST tooling'],['Experience conducting application security assessments, threat modeling, and code security reviews.','Knowledge of common vulnerability classes (SSRF, XSS, SQL injection, deserialization) and their mitigations.','Experience integrating security tooling into CI/CD pipelines (Snyk, SonarQube, Semgrep).'],['Relevant certifications (OSCP, CEH, CISSP, or GPEN).','Experience with bug bounty programs or responsible disclosure.']), wage:130000, wageInterval:'yearly', country:'Germany', city:'Munich', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(18) },
  { title:'Platform Engineer', description:desc('Platform Engineer',['Kubernetes','Helm','GitOps (ArgoCD)','developer tooling'],['Experience building internal developer platforms (IDPs) that improve engineering productivity.','Expertise with Kubernetes operators, custom resource definitions (CRDs), and admission webhooks.','Strong scripting skills (Bash, Python, or Go) for automation and tooling.'],['Experience with Crossplane or Backstage for platform abstractions.','Background in building self-service infrastructure APIs for engineering teams.']), wage:150000, wageInterval:'yearly', country:'Israel', city:'Tel Aviv', isFeatured:true, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(10) },
  { title:'Site Reliability Engineer', description:desc('Site Reliability Engineer',['Go','Prometheus & Grafana','incident management','Linux systems'],['Experience defining and tracking SLOs/SLAs and driving error budget policies.','Proficiency building observability tooling: metrics, structured logging, and distributed tracing (OpenTelemetry).','Strong Linux internals knowledge — you can diagnose CPU, memory, I/O, and network issues under pressure.'],['Experience with chaos engineering tools (Chaos Monkey, Gremlin, or Litmus).','Background writing runbooks and leading blameless postmortem processes.']), wage:145000, wageInterval:'yearly', country:'United Kingdom', city:'London', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(35) },
  { title:'Technical Product Manager', description:desc('Technical Product Manager',['API product management','agile delivery','developer experience','technical roadmapping'],['Demonstrated ability to manage API or platform products that serve internal or external developers.','Comfort reading and writing code (Python, JavaScript, or similar) for prototyping and technical scoping.','Experience writing detailed technical specifications, API contracts, and integration guides.'],['Background as a software engineer who transitioned into product management.','Experience with developer tool or API-first SaaS products.']), wage:115000, wageInterval:'yearly', country:'Germany', city:'Berlin', isFeatured:false, locationRequirement:'in-office', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(14) },
  { title:'Data Engineer', description:desc('Data Engineer',['Apache Spark','dbt','Airflow','Python'],['Experience designing and operating large-scale data pipelines handling terabytes of data daily.','Strong SQL skills and expertise with columnar storage formats (Parquet, Delta Lake, or Iceberg).','Familiarity with modern data warehouse platforms (BigQuery, Snowflake, or Redshift).'],['Experience with real-time streaming pipelines (Apache Kafka or Flink).','Knowledge of data quality frameworks and data contract patterns.']), wage:155000, wageInterval:'yearly', country:'United States', city:'New York', isFeatured:false, locationRequirement:'remote', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(22) },
  { title:'Junior Frontend Developer', description:desc('Junior Frontend Developer',['React','JavaScript','HTML5 & CSS3','Git'],['Foundational understanding of the React component lifecycle, hooks, and JSX.','Ability to implement pixel-perfect UI from Figma designs using modern CSS (Flexbox, Grid).','Eagerness to learn, ask questions, and grow through mentorship and code reviews.'],['Exposure to TypeScript or willingness to learn it quickly.','Personal projects, bootcamp portfolio, or contributions to open source.']), wage:75000, wageInterval:'yearly', country:'Israel', city:'Jerusalem', isFeatured:false, locationRequirement:'in-office', experienceLevel:'junior', status:'published', type:'full-time', postedAt:daysAgo(45) },
  { title:'Backend Developer (Python)', description:desc('Backend Developer (Python)',['Python','FastAPI','PostgreSQL','Docker'],['Experience building production-grade REST APIs with FastAPI, Django REST Framework, or Flask.','Proficiency with SQLAlchemy or similar ORM for PostgreSQL/MySQL.','Understanding of async Python (asyncio, aiohttp) for high-concurrency services.'],['Experience with Celery or similar task queue systems.','Familiarity with type annotations and static analysis tools (mypy, Ruff, or pyright).']), wage:110000, wageInterval:'yearly', country:'Germany', city:'Hamburg', isFeatured:false, locationRequirement:'remote', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(28) },
  { title:'iOS Engineer', description:desc('iOS Engineer',['Swift','SwiftUI','UIKit','Xcode & Instruments'],['Shipped at least two iOS apps to the App Store with 10k+ monthly active users.','Deep understanding of Swift concurrency (async/await, actors) and memory management (ARC).','Experience with MVVM or TCA architecture patterns in iOS applications.'],['Experience with SwiftData or Core Data for local persistence.','Familiarity with App Clips, Widgets, or other iOS platform extensions.']), wage:180000, wageInterval:'yearly', country:'United States', city:'San Francisco', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(40) },
  { title:'Android Engineer', description:desc('Android Engineer',['Kotlin','Jetpack Compose','Android SDK','Coroutines & Flow'],['Production experience building Android apps with Jetpack Compose and the Android Jetpack suite.','Strong command of Kotlin coroutines, Flow, and structured concurrency.','Experience with clean architecture and dependency injection (Hilt or Koin).'],['Experience with Kotlin Multiplatform Mobile (KMM).','Background optimizing Android app startup time and reducing APK/AAB size.']), wage:165000, wageInterval:'yearly', country:'United States', city:'Austin', isFeatured:false, locationRequirement:'remote', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(55) },
  { title:'Staff Software Engineer', description:desc('Staff Software Engineer',['system design','TypeScript / Go','technical leadership','distributed systems'],['Demonstrated experience leading large cross-team technical initiatives from scoping through delivery.','Expert-level understanding of distributed systems: consensus, CAP theorem, eventual consistency.','Track record of mentoring senior engineers and raising the technical bar across an organization.'],['Published technical writing, conference talks, or open-source project leadership.','Experience as an engineering manager who returned to an individual contributor role.']), wage:230000, wageInterval:'yearly', country:'United States', city:'New York', isFeatured:false, locationRequirement:'in-office', experienceLevel:'senior', status:'published', type:'full-time', postedAt:daysAgo(60) },
  { title:'Junior React Developer', description:desc('Junior React Developer',['React','TypeScript','Tailwind CSS','REST APIs'],['Basic React experience through coursework, bootcamp, or personal projects.','Understanding of component composition, props, and state management fundamentals.','Ability to work independently on well-scoped tasks and communicate blockers proactively.'],['Exposure to testing with Jest or React Testing Library.','Experience with version control workflows (feature branches, pull requests, rebasing.']), wage:null, wageInterval:null, country:'Israel', city:'Tel Aviv', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'junior', status:'published', type:'part-time', postedAt:daysAgo(70) },
  { title:'Infrastructure Engineer', description:desc('Infrastructure Engineer',['Terraform','AWS','Linux','Ansible'],['Experience managing cloud infrastructure at scale (VPCs, EC2, ECS/EKS, RDS, S3, CloudFront).','Proficiency with configuration management tools (Ansible, Chef, or Puppet).','Strong Linux administration skills: systemd, networking, storage, and kernel tuning.'],['Experience with immutable infrastructure patterns and AMI/image pipelines.','Knowledge of cloud security best practices (IAM least privilege, VPC segmentation, KMS).']), wage:125000, wageInterval:'yearly', country:'United Kingdom', city:'Edinburgh', isFeatured:false, locationRequirement:'remote', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(32) },
  { title:'GraphQL API Developer', description:desc('GraphQL API Developer',['GraphQL','Apollo Server','Node.js','TypeScript'],['Experience designing and implementing production GraphQL schemas, including federation across microservices.','Strong understanding of N+1 query problems and mitigation strategies (DataLoader, persisted queries).','Knowledge of GraphQL subscriptions and real-time data delivery patterns.'],['Experience with schema-first tooling (GraphQL Codegen, Pothos, or Nexus).','Background optimizing GraphQL query performance and caching strategies.']), wage:120000, wageInterval:'yearly', country:'Germany', city:'Munich', isFeatured:false, locationRequirement:'remote', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(48) },
  { title:'Analytics Engineer', description:desc('Analytics Engineer',['dbt','SQL','BigQuery / Snowflake','Looker / Metabase'],['Experience building and maintaining dbt projects: models, tests, macros, and documentation.','Deep SQL expertise — window functions, CTEs, performance tuning, and query plan analysis.','Ability to bridge the gap between data engineering and business intelligence.'],['Experience with Looker LookML or similar semantic layer tooling.','Familiarity with data observability platforms (Monte Carlo, Great Expectations).']), wage:105000, wageInterval:'yearly', country:'United Kingdom', city:'London', isFeatured:false, locationRequirement:'hybrid', experienceLevel:'mid-level', status:'published', type:'full-time', postedAt:daysAgo(38) },
  { title:'Frontend Engineering Intern', description:desc('Frontend Engineering Intern',['React','JavaScript','HTML & CSS','Git & GitHub'],['Currently pursuing a degree in Computer Science, Software Engineering, or a related field.','Completed at least one React project (coursework, personal, or open source).','Excellent communication and willingness to ask questions and iterate quickly.'],['Exposure to TypeScript or interest in typed JavaScript.','Participation in hackathons, coding challenges, or university engineering clubs.']), wage:45, wageInterval:'hourly', country:'Israel', city:'Haifa', isFeatured:false, locationRequirement:'in-office', experienceLevel:'junior', status:'published', type:'internship', postedAt:daysAgo(82) },
];

async function restore(): Promise<void> {
  console.log('--- restoreSoftwareCompany ---');
  try {
    // 1. Re-insert the org
    await pool.query(
      `INSERT INTO organizations (id, name, "imageUrl", "createdAt", "updatedAt")
       VALUES ($1, $2, '', NOW(), NOW())
       ON CONFLICT (id) DO NOTHING`,
      [ORG_ID, ORG_NAME]
    );
    console.log(`✓ Org inserted: "${ORG_NAME}" (${ORG_ID})`);

    // 2. Ensure primary employer user exists (may be missing if Inngest was offline)
    await pool.query(
      `INSERT INTO users (id, name, email, "imageUrl", "createdAt", "updatedAt")
       VALUES ($1, 'Primary Employer', 'employer@careerbridge.dev', '', NOW(), NOW())
       ON CONFLICT (id) DO NOTHING`,
      [PRIMARY_EMPLOYER_ID]
    );

    // 3. Org-user settings for primary employer
    await pool.query(
      `INSERT INTO organization_user_settings ("userId", "organizationId", "newApplicationEmailNotifications", "createdAt", "updatedAt")
       VALUES ($1, $2, true, NOW(), NOW())
       ON CONFLICT ("userId", "organizationId") DO NOTHING`,
      [PRIMARY_EMPLOYER_ID, ORG_ID]
    );
    console.log(`✓ Org-user settings set for primary employer`);

    // 4. Insert the 25 listings
    for (const l of LISTINGS) {
      await pool.query(
        `INSERT INTO job_listings
           ("organizationId", title, description, wage, "wageInterval",
            country, city, "isFeatured", "locationRequirement",
            "experienceLevel", status, type, "postedAt")
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,
        [ORG_ID, l.title, l.description, l.wage, l.wageInterval, l.country, l.city,
         l.isFeatured, l.locationRequirement, l.experienceLevel, l.status, l.type, l.postedAt]
      );
    }
    console.log(`✓ Inserted ${LISTINGS.length} listings for "${ORG_NAME}"`);
    console.log('\nDone. Both organizations are now active:');
    console.log(`  Software Company      → ${LISTINGS.length} listings`);
    console.log(`  Digital Products LTD  → 12 listings`);
  } catch (err) {
    console.error('Restore failed:', err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

restore();
